"""empty message

Revision ID: 5377b93239a9
Revises: b21782277b21
Create Date: 2024-12-05 22:33:37.144611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5377b93239a9'
down_revision = 'b21782277b21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_liquidity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('yes_liquidity', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('no_liquidity', sa.Float(), nullable=False))
        batch_op.drop_column('no_balance')
        batch_op.drop_column('yes_balance')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_liquidity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('yes_balance', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('no_balance', sa.FLOAT(), nullable=False))
        batch_op.drop_column('no_liquidity')
        batch_op.drop_column('yes_liquidity')

    # ### end Alembic commands ###
