"""empty message

Revision ID: b21782277b21
Revises: 
Create Date: 2024-12-03 11:24:31.380261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b21782277b21'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prediction_market',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=1025), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column("resolved", sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prediction_market', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prediction_market_created_at'), ['created_at'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('api_key', sa.String(length=256), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('market_liquidity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('yes_balance', sa.Float(), nullable=False),
    sa.Column('no_balance', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['prediction_market.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('market_liquidity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_liquidity_market_id'), ['market_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_liquidity_timestamp'), ['timestamp'], unique=False)

    op.create_table('user_balance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('yes_balance', sa.Float(), nullable=False),
    sa.Column('no_balance', sa.Float(), nullable=False),
    sa.Column('dog_balance', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['prediction_market.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_balance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_balance_market_id'), ['market_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_balance_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_balance_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_balance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_balance_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_balance_timestamp'))
        batch_op.drop_index(batch_op.f('ix_user_balance_market_id'))

    op.drop_table('user_balance')
    with op.batch_alter_table('market_liquidity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_liquidity_timestamp'))
        batch_op.drop_index(batch_op.f('ix_market_liquidity_market_id'))

    op.drop_table('market_liquidity')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('prediction_market', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prediction_market_created_at'))

    op.drop_table('prediction_market')
    # ### end Alembic commands ###
