"""init

Revision ID: bc598246d09d
Revises: 
Create Date: 2024-12-01 20:45:04.542584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc598246d09d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prediction_market',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=1025), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('transaction_in_prediction_market',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('tx_type', sa.String(length=8), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('price_yes_after', sa.Float(), nullable=False),
    sa.Column('price_no_after', sa.Float(), nullable=False),
    sa.Column('yes_shares_in_liquidity_pool_after', sa.Float(), nullable=False),
    sa.Column('no_shares_in_liquidity_pool_after', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['prediction_market.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction_in_prediction_market', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_in_prediction_market_market_id'), ['market_id'], unique=False)

    op.create_table('transaction_user',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tx_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tx_id'], ['transaction_in_prediction_market.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_user')
    with op.batch_alter_table('transaction_in_prediction_market', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_in_prediction_market_market_id'))

    op.drop_table('transaction_in_prediction_market')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('prediction_market')
    # ### end Alembic commands ###
